### ISSUE TITLE
Show appropriate error when a character is drawn instead of a digit

### ISSUE THREAD

**Issue by iamShantanu101** [luisvalesilva/digitre#2]
Hi,

Is it possible to show appropriate error message when the user accidentally draws a character instead of a digit. At the moment, it is also classifying characters as digits which doesn't give expected results.

**Comment by luisvalesilva** [comment]
The model always outputs a probability distribution across the 10 possible classes (digits 0, 1, 2, ..., 9), with the combined probabilities adding up to 1. This is the case even if the input is far from any training example.

The output class probabilities may be very high even if the input is not a digit. Basically, the model may settle on a specific class with no ambiguity and thus output a high probability for that class.

**Comment by iamShantanu101** [comment]
So this is how CNN model works in this case, right? Wouldn't this limit the real world applications? Or there are alternative ways like RNNs?

**Comment by luisvalesilva** [comment]
It can only classify digits, yeah. But for this particular application CNNs get the best results, as you can see in the curated benchmark lists ([MNIST](http://yann.lecun.com/exdb/mnist/), [Classification datasets results - MNIST](http://rodrigob.github.io/are_we_there_yet/build/classification_datasets_results.html#4d4e495354)).

Check out my [blog post](http://luisvalesilva.com/datasimple/digitre.html) for more details about the app.
